"""使い方の動画（/howto）の中身。1 問 1 本の短い動画を、題を押したときだけ読み込む。

- 動画は X 向けに撮った 1 機能 1 本のもの（`promo/out/x/<id>.mp4`。台本は `promo/x_catalog*.mjs`）。
  答えの文は台本の `what` を元に、使い方のページの口調へ直したもの
- **動画は R2 から配る**（1 本 0.1〜5MB、全部で 100MB ほど。Render から出すと転送量が課金される）。
  `scripts/upload_howto_r2.py` が `howto/<id>.<ハッシュ>.mp4` に上げ、どの id がどのキーかを
  `backend/howto_videos.json` に書く。**表に無い id（まだ上げていない動画）の問いはページに出さない**
- GIF にはしない。同じ動画で GIF は MP4 の約 4 倍（`color-sort`: 9.8MB 対 2.3MB。2026-09-26 に実測）
- 画面が変わって動画と食い違ったら、撮り直して上げ直す（名前にハッシュが入るので、古いキャッシュは踏まない）

1 問 = (id, 日本語の問い, 日本語の答え, 英語の問い, 英語の答え)。答えの `{days}` は共有の保持日数に置き換える。
"""
from __future__ import annotations

import json
from pathlib import Path

MANIFEST = Path(__file__).resolve().parent / "howto_videos.json"

# X 向けに撮ったが、ここには出さないもの（見た目の紹介で問いにならないもの、ほかの問いと中身が重なるもの）:
# p-os9・p-logo・p-counts（見た目の紹介）、lang（o-lang-us と重なる）、zoom-wheel（o-zoom と重なる）
SECTIONS: list[tuple[str, str, list[tuple[str, str, str, str, str]]]] = [
    ("トラックを入れる", "Adding tracks", [
        ("f-search", "トラックを探して入れるには？",
         "検索欄にトラック名やアーティスト名を入れて探し、候補を押すと空いているマスに入ります。候補には、どこから取ってきたかを示す札が付きます。",
         "How do I find a track and add it?",
         "Search by track title or artist name, then press a result to put it in an empty cell. Each result has a tag showing where it came from."),
        ("f-sources", "ボカロ曲や音MADを探したいです。",
         "「ソース」を VocaDB にするとボカロの原曲が、otoDB にすると音MADが見つかります。otoDB では、削除された動画のサムネイルも出ます。",
         "I want to find Vocaloid songs or otomad.",
         "Set “Sources” to VocaDB for original Vocaloid songs, or to otoDB for otomad. otoDB also shows thumbnails of deleted videos."),
        ("f-url", "動画やストアのページから直接入れられますか？",
         "ページの URL を貼ると、そのトラックを取り込めます。ニコニコ動画なら、sm から始まる ID だけでも入れられます。",
         "Can I add a track straight from a video or store page?",
         "Paste the page URL to import that track. For Niconico, the ID starting with “sm” is enough."),
        ("f-multi-url", "URL をいくつもまとめて入れられますか？",
         "1 行に 1 つずつ貼れば、まとめて取り込めます。YouTube・SoundCloud・Bandcamp など、違うサイトの URL が混ざっていてもかまいません。",
         "Can I add several URLs at once?",
         "Paste one URL per line to import them all together. They can come from different sites, such as YouTube, SoundCloud and Bandcamp."),
        ("f-playlist", "プレイリストを丸ごと入れるには？",
         "マイリストや再生リストの URL を 1 つ貼るだけで、最大 500 曲をまとめて取り込めます。「マスに入れる」を押すと、順にマスが埋まります。",
         "How do I import a whole playlist?",
         "Paste the URL of a mylist or playlist to import up to 500 tracks at once. Press “Fill the grid” to fill the cells in order."),
        ("f-playlist-pick", "プレイリストの中から好きな曲だけ選べますか？",
         "まとめて取り込んだあとに「候補に置いて選ぶ」を押すと、曲が候補に並びます。そこから入れたいものだけを選べます。",
         "Can I pick only some tracks from a playlist?",
         "After importing, press “Put in results and pick” to list the tracks as results. Then add only the ones you want."),
        ("f-list", "曲名のリストから一気に入れたいです。",
         "「トラック名の一覧から」の表にアーティスト名とトラック名を入れて「一覧から入れる」を押すと、iTunes で 1 行ずつ探し、ぴったり合ったものをマスに入れます。",
         "I want to add tracks from a list of titles.",
         "Enter artist and track names in the table under “From a list of track names” and press “Add from list”. Each row is looked up on iTunes, and exact matches go into the cells."),
        ("f-copy-paste", "並びを曲名の一覧としてコピーできますか？",
         "「トラック名をコピー」で、番号付きの一覧としてコピーできます。これを表に貼ると、行と列に分かれて戻ります。Excel などの表も同じように貼れます。",
         "Can I copy the layout as a list of track names?",
         "“Copy track names” copies a numbered list. Paste it back into the table and it splits into rows and columns again. Tables from Excel and similar apps can be pasted the same way."),
        ("o-sub", "検索のほかにどんな入れ方がありますか？",
         "「URL から」「トラック名の一覧から」「手入力」の 3 つがあります。見出しを押すと切り替わります。",
         "What other ways are there to add tracks besides searching?",
         "There are three: “From a URL”, “From a list of track names” and “By hand”. Press a heading to switch between them."),
        ("f-manual", "手元の画像をジャケットにしたいです。",
         "「端末から画像を選択…」で画像を選び、トラック名とアーティスト名を入れて追加します。撮影日時などの情報は消してから保存します。",
         "I want to use an image from my device as the cover.",
         "Pick an image with “Choose an image from this device…”, enter the track and artist names, and add it. Information such as the date the photo was taken is removed before saving."),
        ("o-spotify", "Spotify の URL だとアーティスト名が出ません。",
         "Spotify からはアーティスト名が取れないため、iTunes で同じトラック名の曲を探して補います。候補が何人かいるときは、その中から選べます。",
         "The artist name is missing for a Spotify URL.",
         "Spotify doesn't provide the artist name, so TRACKMENTO looks up a track with the same title on iTunes. If there are several candidates, you can choose one."),
        ("o-revive", "削除されたニコニコ動画も入れられますか？",
         "otoDB に登録があれば、題とサムネイルを取り込めます。マイリストの中の削除済みの動画も補います。",
         "Can I add a deleted Niconico video?",
         "If the work is registered on otoDB, its title and thumbnail can be imported. Deleted videos inside a mylist are filled in too."),
        ("o-same", "同じ曲を 2 回入れてしまったら？",
         "「N 番にも同じトラックがあります」とお知らせします。入れること自体は止めないので、わざと並べることもできます。",
         "What if I add the same track twice?",
         "You'll see a message that the same track is already in another cell. It doesn't stop you, so you can repeat a track on purpose."),
        ("o-target", "入れるマスを先に決めてから探せますか？",
         "空いているマスを押すと、そのマスが「入れる先」になります。次に押した候補が、そのマスに入ります。",
         "Can I choose the cell first and then search?",
         "Press an empty cell to make it the target. The next result you press goes into that cell."),
    ]),
    ("並べ替える・直す", "Arranging and editing", [
        ("o-swap", "マスを入れ替えるには？",
         "マスを押して選び、別のマスを押すと入れ替わります。空いているマスを押せば、そこへ移ります。もう一度同じマスを押すと、選ぶのをやめます。",
         "How do I swap two cells?",
         "Press a cell to select it, then press another cell to swap them. Press an empty cell to move the track there. Press the same cell again to cancel."),
        ("o-drag", "ドラッグで動かせますか？",
         "PC では、マスを掴んで運ぶと入れ替わります。",
         "Can I drag tracks around?",
         "On a computer, drag a cell onto another to swap them."),
        ("alt-arrows", "キーボードだけで並べ替えられますか？",
         "矢印キーでマスを移り、Alt（Mac は Option）＋矢印キーで、トラックを持ったまま隣へ運べます。",
         "Can I rearrange with only the keyboard?",
         "Move between cells with the arrow keys, and press Alt (Option on a Mac) + an arrow key to carry the track to the next cell."),
        ("o-keys", "キーボードで操作できますか？",
         "Tab でグリッドへ移り、矢印キーでマスを移動、Return で選び、Esc でやめます。",
         "Can I use TRACKMENTO with a keyboard?",
         "Press Tab to reach the grid, move between cells with the arrow keys, press Return to select and Esc to cancel."),
        ("o-remove", "マスからトラックを外すには？",
         "マスの × を押すと外れます。外したあとのメッセージにある「元に戻す」で戻せます。",
         "How do I remove a track from a cell?",
         "Press the × on the cell. Press “Undo” in the message that appears to bring it back."),
        ("o-clear", "全部外してやり直したいです。",
         "「トラックを全て外す」を押すと確認の窓が出ます（最初は「やめる」が選ばれています）。外したあとも「元に戻す」で戻せます。",
         "I want to clear everything and start over.",
         "Press “Remove all tracks” and a confirmation window appears (“Cancel” is selected at first). Even after removing, you can bring them back with “Undo”."),
        ("undo-buttons", "操作を取り消せますか？",
         "グリッドの下の「元に戻す」「やり直す」で、30 回まで戻せます。戻したものをやり直すこともできます。スマホでも使えます。",
         "Can I undo what I did?",
         "Use “Undo” and “Redo” below the grid to go back up to 30 steps, and to redo what you undid. They work on phones too."),
        ("undo-keys", "キーボードで取り消せますか？",
         "Ctrl+Z（Mac は ⌘+Z）で 1 手ずつ戻せます。30 手まで戻れます。",
         "Can I undo with the keyboard?",
         "Press Ctrl+Z (⌘+Z on a Mac) to go back one step at a time, up to 30 steps."),
        ("o-grid-size", "マスの数を変えるには？",
         "「横 × 縦」の数を、上下の小さな矢印で増やしたり減らしたりできます。マスは全部で 256 までです。",
         "How do I change the number of cells?",
         "Use the small up and down arrows next to the columns and rows. The grid can have up to 256 cells in total."),
        ("p-care", "マスを増やしすぎるとどうなりますか？",
         "マスは合計 256 までです。横 × 縦を大きくしすぎたときは、自動で縮めてお知らせします。",
         "What happens if I add too many cells?",
         "The grid can have up to 256 cells. If the columns × rows go over that, they are reduced automatically and you'll see a message."),
        ("stash", "マスを減らすと、はみ出た曲は消えますか？",
         "消えません。いったん外して取っておき、マスの数を戻すと帰ってきます。",
         "Do tracks disappear when I make the grid smaller?",
         "No. They are set aside, and they come back when you make the grid larger again."),
        ("o-editor", "トラック名やアーティスト名を直したいです。",
         "マスを選ぶと、トラック名とアーティスト名を直せます。メモを書くと、共有ページのトラックリストに出ます。",
         "I want to correct a track title or artist name.",
         "Select a cell to edit its track title and artist name. A note you write there appears in the track list on the share page."),
        ("o-origin", "アーティスト名がチャンネル名になっています。",
         "動画サイトの曲では、アーティスト名がチャンネル名になっていることがあります。「元の投稿を探す」を押すと、otoDB やニコニコ動画の古い投稿から作者を探して選べます。",
         "The artist name shows the channel name.",
         "For tracks from video sites, the artist name is sometimes the channel name. Press “Find the original post” to look for the creator in otoDB and older Niconico uploads, and choose one."),
        ("o-trim", "曲名に付いている【】や「- Topic」を消したいです。",
         "「トラック名を短くする」で、【東方Vocal】や「- Topic」のような部分を外せます。書き出す画像の曲名リストもすっきりします。",
         "I want to remove tags like 【…】 or “- Topic” from titles.",
         "“Shorten all titles” removes parts such as 【東方Vocal】 or “- Topic”. The track list in the exported image gets tidier too."),
        ("color-sort", "ジャケットの色で並べられますか？",
         "「色で並べ替え」で、サムネイルの主な色をもとに赤から紫の順に並べ直します。白黒のサムネイルは明るい順に並びます。",
         "Can I sort by cover color?",
         "“Sort by color” rearranges the tracks from red to violet by the main color of each thumbnail. Black-and-white thumbnails are sorted by brightness."),
        ("o-zoom", "マスが多くて見づらいです。",
         "「大きく見る」でグリッドを画面いっぱいに広げられます。窓の中を送って見られ、2 本指（Ctrl＋ホイール）でマスの大きさも変えられます。大きさは並びの形ごとに覚えます。",
         "The grid is hard to see with many cells.",
         "“Enlarge” shows the grid full-screen. You can scroll inside it and change the cell size with two fingers (Ctrl + wheel). The size is remembered for each grid shape."),
    ]),
    ("並びを管理する", "Managing layouts", [
        ("o-theme", "お題から作れますか？",
         "「お題」から選ぶとタイトルが入ります。「私を構成する9曲」を選ぶと、横 × 縦も 3 × 3 になります。",
         "Can I start from a theme?",
         "Choose one from “Theme” to fill in the title. Choosing “9 tracks that made me” also sets the grid to 3 × 3."),
        ("o-layouts", "並びをいくつも作れますか？",
         "「並び」は 10 個まで持てます。「新しい並び」で別の並びを作り、メニューで切り替えます。",
         "Can I keep several layouts?",
         "You can keep up to 10 layouts. Create another with “New layout” and switch between them from the menu."),
        ("o-json", "並びを長く残しておきたいです。",
         "共有は {days} 日で消えるので、長く残したいときは「並びを保存」でファイルに書き出してください。「並びを読み込み…」で同じ並びに戻せます。",
         "I want to keep a layout for a long time.",
         "Shares are deleted after {days} days, so use “Save layout” to save it as a file. “Load layout…” brings the same layout back."),
        ("o-share-open", "共有した並びを手直ししたいです。",
         "共有ページの「TRACKMENTO で開く」を押すと、その並びが新しい並びとして入ります。今の並びはそのまま残り、「並び」のメニューで戻れます。",
         "I want to revise a grid I shared.",
         "Press “Open in TRACKMENTO” on the share page to add that layout as a new layout. Your current layout stays as it is, and you can go back to it from the “Layout” menu."),
    ]),
    ("書き出す画像の見た目", "How the image looks", [
        ("s-ratio", "画像の形を変えたいです。",
         "「全体枠」で、正方形 1:1・インスタ 4:5・横長 16:9・縦長 9:16 などから選べます。",
         "I want to change the shape of the image.",
         "Choose from square 1:1, Instagram 4:5, wide 16:9, tall 9:16 and more under “Image frame”."),
        ("cell-ratio", "動画のサムネイルが左右で切れてしまいます。",
         "「マス枠」を横長 16:9 にすると、動画サイトのサムネイルが切れずに並びます。",
         "Video thumbnails get cut off at the sides.",
         "Set “Cell frame” to wide 16:9 so video thumbnails fit without being cropped."),
        ("cell-fit", "形の違うサムネイルを切らずに入れたいです。",
         "「サムネ余白」を「ぼかし背景」にすると、形の違うサムネイルも切らずに入ります。",
         "I want thumbnails of different shapes to fit without cropping.",
         "Set “Thumbnail fill” to “Blurred backdrop” so thumbnails of any shape fit without being cropped."),
        ("s-fit-one", "1 つのマスだけ入れ方を変えられますか？",
         "マスを選ぶと、そのマスだけサムネイルの入れ方を変えられます。たとえば横長のマスに、正方形のサムネイルを切らずにぼかして入れられます。",
         "Can I change how just one cell is filled?",
         "Select a cell to change how its thumbnail is fitted. For example, you can put a square thumbnail in a wide cell without cropping, with a blurred backdrop."),
        ("o-tri", "出力オプションの項目が見つかりません。",
         "出力オプションは「マス」「文字」「背景と余白」のまとまりに分かれています。枠の形は「枠とサムネ」の三角を押すと開きます。",
         "I can't find a setting in the output options.",
         "The output options are grouped into “Cells”, “Text” and “Background and spacing”. The frame settings open when you press the triangle next to “Frames and thumbnails”."),
        ("s-labels", "タイトルや番号を消せますか？",
         "「表示」で、タイトル・番号バッジ・トラック名の省略表示を切り替えられます。",
         "Can I hide the title or the numbers?",
         "Under “Show”, you can turn the title, number badges and shortened track names on or off."),
        ("r-tracklist", "曲名リストの出し方は選べますか？",
         "「トラックリスト」は、横並び・サムネイルに重ねる・出さないの 3 通りから選べます。",
         "Can I choose how the track list is shown?",
         "“Track list” has three styles: beside the grid, over the thumbnails, or hidden."),
        ("r-layouts", "曲名リストの組み方が毎回変わります。",
         "曲名リストの組み方は、横 × 縦と曲の数に合わせて自動で変わります（マスの横・帯の下・表・流し込み）。書き出すたびに組み直します。",
         "The track list is arranged differently each time.",
         "The track list layout changes automatically to suit the columns × rows and the number of tracks (beside the cells, under a band, as a table, or flowing). It is rearranged every time you export."),
        ("r-empty", "空いたマスはどう書き出されますか？",
         "空いたマスは塗らずに書き出します。番号は、曲の入ったマスだけに 01 から詰めて振ります。",
         "How are empty cells exported?",
         "Empty cells are left blank. Numbers are given only to cells with tracks, counting from 01 without gaps."),
        ("s-pad-gap", "余白やすき間を変えたいです。",
         "「余白」（ふつう・ひろめ・たっぷり）と「マスの間隔」で、詰まり具合を変えられます。",
         "I want to change the margins and spacing.",
         "Adjust how tight the image looks with “Margin” (Normal, Wide, Extra wide) and “Gap”."),
        ("r-output", "共有する前に仕上がりを見られますか？",
         "「できあがり」の窓で「更新」を押すと、書き出す画像の見本ができます（共有はしません）。見本を押すと大きく見られます。",
         "Can I see the result before sharing?",
         "Press “Refresh” in the “Result” window to make a preview of the exported image (nothing is shared). Press the preview to see it larger."),
    ]),
    ("背景", "Background", [
        ("s-bg-preview", "背景にはどんな種類がありますか？",
         "色の選択・サムネの近似色・サムネの補色・グラデーション・画像・透過から選べます。",
         "What kinds of background are there?",
         "Choose a color, match the thumbnails, complement the thumbnails, gradient, image or transparent."),
        ("s-swatch", "背景の色を選びたいです。",
         "見本の 8 色から選べます。「カスタムカラー」では、色相・彩度・明度を好きに決められます。",
         "I want to choose the background color.",
         "Pick one of the 8 sample colors, or set any hue, saturation and brightness with “Custom color”."),
        ("bg-modes", "ジャケットに合う色を背景にできますか？",
         "「背景」で「サムネの近似色」や「サムネの補色」を選ぶと、並んだサムネイルから色を取ります。",
         "Can the background match the covers?",
         "Choose “Match the thumbnails” or “Complement the thumbnails” under “Background” to take the color from the thumbnails in the grid."),
        ("s-grad", "背景をグラデーションにしたいです。",
         "「グラデーション」はサムネイルの色から作ります。「ほかの模様」を押すと、揺らぎの形だけが変わります。色を自分で選ぶこともできます。",
         "I want a gradient background.",
         "“Gradient” is made from the colors of the thumbnails. “Another pattern” changes only the shape of the swirl. You can also pick the colors yourself."),
        ("bg-image", "好きな画像を背景にしたいです。",
         "「画像」を選ぶと、まず TRACKMENTO の模様が敷かれます。「画像を選ぶ…」で端末の画像に替えられます。曲名が読めるように、にぎやかな画像ほど薄く敷きます。",
         "I want to use my own image as the background.",
         "Choosing “Image” first lays down the TRACKMENTO pattern. Replace it with an image from your device using “Choose an image…”. Busier images are laid more faintly so the titles stay readable."),
        ("s-img-tile", "背景の画像を並べて敷けますか？",
         "背景の画像は、全体表示かタイル（小・中・大）で敷けます。",
         "Can I tile the background image?",
         "The background image can be shown to fit the whole image, or as small, medium or large tiles."),
        ("s-none", "背景を透明にできますか？",
         "「透過」にすると、背景が透明な PNG で保存できます。字の色は黒と白から選べます。",
         "Can the background be transparent?",
         "Choose “Transparent” to save a PNG with a transparent background. The text can be black or white."),
    ]),
    ("共有する", "Sharing", [
        ("f-share", "画像を共有するには？",
         "「トラックを共有」を押すと、画像と共有 URL ができます。共有ページでは、曲名からそれぞれのページへ移れます。共有は {days} 日で消えます。",
         "How do I share the image?",
         "Press “Share these tracks” to create the image and a share URL. On the share page, each track title links to its page. Shares are deleted after {days} days."),
        ("f-find", "ほかの人のグリッドを見られますか？",
         "共有するときに「みんなのグリッドに載せる」にチェックを入れると、トラック名やアーティスト名で探せるようになります。自分が載せた並びは × で外せます。",
         "Can I see other people's grids?",
         "If you check “Add to everyone's grids” when sharing, others can find your grid by track title or artist name. You can take your own grids off the list with ×."),
    ]),
    ("画面", "The screen", [
        ("o-lang-us", "英語で使えますか？",
         "右上の「EN」で英語表示になります。英語表示で探すと、iTunes の米国の表記でトラック名とアーティスト名が出ます。もう一度押すと日本語に戻ります。",
         "Can I use it in English?",
         "Press “EN” at the top right to switch to English. Searches in English show track and artist names as they appear in the US iTunes store. Press it again to go back to Japanese."),
        ("o-window", "窓を動かせますか？",
         "PC では、窓を題名バーで掴んで動かせます。右上の「—」で畳めます。「窓を元に戻す」で元の位置に戻ります。",
         "Can I move the windows?",
         "On a computer, drag a window by its title bar. Collapse it with “—” at the top right. “Reset windows” puts them back."),
        ("s-palette", "画面の色を変えたいです。",
         "「配色パレットを選ぶ…」で、画面全体の色が替わります。「ナイト」は暗い地で、OS 9 風の部品まで暗くなります。",
         "I want to change the colors of the screen.",
         "“Choose a color palette…” changes the colors of the whole screen. “Night” uses a dark background, and even the OS 9-style controls turn dark."),
        ("s-pal-make", "自分で配色を作れますか？",
         "「いまの色から作る」で自分の配色を作れます。色を押して、つまみで直します。カラーコードを貼って作ることもできます。",
         "Can I make my own color scheme?",
         "Use “Create from current colors”. Press a color and adjust it with the sliders. You can also paste color codes."),
        ("p-small", "マスが小さいと × や曲名が出ません。",
         "マスが小さくなると、× と番号と曲名の帯を隠して、サムネイルを見せます。マスを押せば、編集の欄で直せます。",
         "The × and titles disappear when cells are small.",
         "When cells get small, the ×, number and title band are hidden so you can see the thumbnails. Press a cell to edit it in the edit panel."),
    ]),
    ("スマホで使う", "On a phone", [
        ("sp-sheet", "スマホで曲を探すには？",
         "「トラックを探す」を押すと、検索のシートが開きます。空いているマスを押すと、そのマスに入れるトラックを探せます。",
         "How do I search for tracks on a phone?",
         "Press “Find a track” to open the search sheet. Press an empty cell to search for a track to put in that cell."),
        ("sp-editor", "スマホで曲名を直したいです。",
         "マスを押すと、グリッドのすぐ下に編集の欄が出ます。トラック名を直したり、そのマスだけサムネイルの入れ方を変えたりできます。",
         "I want to edit a title on a phone.",
         "Press a cell and the edit panel appears right below the grid. You can fix the track title or change how the thumbnail fits in that cell."),
        ("sp-scroll", "スマホのスクロールバーはどう使いますか？",
         "上下の三角で少しずつ、つまみを掴めば一気に送れます。",
         "How does the scroll bar work on a phone?",
         "Press the triangles to scroll a little at a time, or drag the thumb to scroll quickly."),
        ("sp-slider", "スマホでスライダーに触れると値が変わってしまいませんか？",
         "スライダーは、つまみを掴んだときだけ動きます。ページを送ろうとして溝に触れても、値は変わりません。",
         "Do sliders change when I touch them by accident on a phone?",
         "Sliders move only when you grab the thumb. Touching the track while scrolling the page doesn't change the value."),
        ("sp-view", "スマホで PC の画面にできますか？",
         "ページのいちばん下の「PC 版の表示」で PC の画面になります。「スマホ版の表示」で戻ります。",
         "Can I use the desktop layout on a phone?",
         "Press “Desktop view” at the very bottom of the page. “Mobile view” switches back."),
        ("sp-share-target", "YouTube のアプリから直接送れますか？",
         "Android でホーム画面に追加しておくと、YouTube などの「共有」から TRACKMENTO に URL を送れます。送ると自動で取り込みます。この動画だけは、実際の YouTube の画面と、TRACKMENTO の作者の動画を使っています。",
         "Can I send a track straight from the YouTube app?",
         "On Android, add TRACKMENTO to your home screen, and you can send URLs to it from “Share” in YouTube and other apps. They are imported automatically. This video alone uses the real YouTube page and a video by the author of TRACKMENTO."),
        ("sp-inapp", "X や LINE から開くとうまく動きません。",
         "アプリの中のブラウザでは、保存や共有がうまく動かないことがあります。そのため、ブラウザで開き直す案内と「URL をコピー」を出しています。",
         "It doesn't work well when opened from X or LINE.",
         "Saving and sharing may not work in the in-app browser, so TRACKMENTO shows how to reopen it in your browser along with a “Copy URL” button."),
    ]),
]


def videos() -> dict[str, str]:
    """id → R2 のキー（`scripts/upload_howto_r2.py` が書く）。まだ無ければ空"""
    try:
        return json.loads(MANIFEST.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def ids() -> list[str]:
    return [q[0] for _, _, qs in SECTIONS for q in qs]
