import { chromium } from "playwright";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 412, height: 915 }, deviceScaleFactor: 2.625, isMobile: true, hasTouch: true, locale: "ja-JP" });
const page = await ctx.newPage();
await page.goto("http://127.0.0.1:8000/", { waitUntil: "networkidle" });
await page.waitForTimeout(1800);
await page.evaluate(() => { for (const p of document.querySelectorAll('.pane[data-collapsed="true"]')) p.dataset.collapsed = "false"; document.querySelector("#margin").scrollIntoView({ block: "center" }); });
await page.waitForTimeout(300);
const b = await page.evaluate(() => { const e = document.querySelector("#margin"), r = e.getBoundingClientRect(); const t = (e.value - e.min) / (e.max - e.min); return { y: r.y, h: r.height, cx: r.left + 9.5 + t * (r.width - 19) }; });
await page.mouse.move(b.cx, b.y + b.h / 2); await page.mouse.down(); await page.mouse.move(b.cx + 20, b.y + b.h / 2, { steps: 4 }); await page.mouse.up();
await page.waitForTimeout(200);
const outline = () => page.evaluate(() => { const e = document.querySelector("#margin"); const cs = getComputedStyle(e); return { fv: e.matches(":focus-visible"), outline: cs.outlineStyle + " " + cs.outlineWidth, cls: e.className }; });
console.log("掴んだ後 :", JSON.stringify(await outline()));
await page.keyboard.press("ArrowRight");
await page.waitForTimeout(150);
console.log("矢印キー後:", JSON.stringify(await outline()), "値", await page.locator("#margin").inputValue());
await ctx.close(); await browser.close();
