import { chromium } from "playwright";
const b = await chromium.launch();
const pg = await b.newPage({ viewport: { width: 1280, height: 900 } });
await pg.goto("http://127.0.0.1:8000/", { waitUntil: "networkidle" });
await pg.evaluate(() => { document.querySelector("#palette-btn").click(); });
await pg.waitForTimeout(400);
await pg.screenshot({ path: process.argv[2] || "pal-riso.png" });
await pg.evaluate(() => { [...document.querySelectorAll(".pal-lane")][1].querySelector(".btn").click(); });
await pg.waitForTimeout(400);
await pg.screenshot({ path: process.argv[3] || "pal-pop.png" });
await b.close();
