import { chromium } from "playwright";
const out = process.argv[2];
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1100, height: 800 }, deviceScaleFactor: 4, locale: "ja-JP" });
const page = await ctx.newPage();
await page.goto("http://127.0.0.1:8000/", { waitUntil: "networkidle" });
await page.waitForTimeout(2200);
const bar = page.locator(".pane-title").first();
const b = await bar.boundingBox();
await page.screenshot({ path: out, clip: { x: b.x, y: b.y - 1, width: Math.min(300, b.width), height: b.height + 2 } });
await ctx.close(); await browser.close();
